#Reed Ceniviva, CIS3207 - Project 2 Simple Shell
#Lab 3:00 pm on Wednesdays SERC 204
all: myshell cd clr dir echo environ pause
	
myshell:
	gcc myShell.c -o myShell

cd:
	gcc -o cd cd.c

clr:
	gcc -o clr clr.c

dir:
	gcc -o dir dir.c

echo:
	gcc -o echo echo.c

environ:
	gcc -o environ environ.c

pause:
	gcc -o pause pause.c
